name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Firebase
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOMUSTREAM }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/service-account.json
          npx firebase-tools deploy --only hosting --project somustream-95d00
